export const SKILLS = [
  'Javascript',
  'Typescript',
  'CSS', 
  'Graphql',
  'React.js',
  'Styled Components',
  'Tailwind CSS',
  'Next.js',
  'Redux',
  'Express.js',
  'Node.js',
  'Java',
  'Spring Boot',
  'ElasticSearch',
  'AWS',
  'Docker',
  'kubernetes',
]